version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: integration_aws_test
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,sqs
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./.localstack:/var/lib/localstack
