name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Start LocalStack
        run: docker-compose up -d

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install behave

      - name: Run pylint
        run: |
          pylint --fail-under=7 app services tests

      - name: Run unittest
        run: python -m unittest

      - name: Run integration tests (pytest)
        run: |
          coverage run -m pytest tests/
          coverage report -m

      - name: Run BDD tests (behave)
        env:
          PYTHONPATH: ./app
        run: behave

      - name: Stop Docker
        if: always()
        run: docker-compose down
